<?php
/**
 * UltraCache 3.12 JavaScript policy contract.
 *
 * Development/CI metadata only. This file is never loaded by WordPress.
 */

declare(strict_types=1);

return array(
    'contract_version' => '3.13.10',
    'lanes' => array('native', 'defer', 'delay'),
    'principles' => array(
        'every_executable_script_has_exactly_one_lane',
        'visible_lists_are_authoritative',
        'generic_engine_does_not_use_vendor_identity_as_hidden_policy',
        'scanner_findings_become_visible_policy_not_hidden_overrides',
        'generic_heuristics_do_not_promote_delay_to_defer',
        'diagnostics_add_no_production_requests_when_disabled',
        'central_router_is_registered_script_lane_authority',
        'route_application_does_not_make_policy_decisions',
        'ultracache_frontend_runtime_has_one_canonical_module_registry',
        'runtime_created_scripts_are_routed_before_execution',
        'registered_and_runtime_scripts_share_one_declarative_policy_table',
        'runtime_scan_detects_unclassified_script_request_escapes',
        'registered_dependency_graph_preserves_lane_execution_order',
    ),
    'router' => array(
        'registered_script_entry_point' => 'ultracache_build_registered_script_route',
        'route_application' => 'ultracache_apply_registered_script_route',
        'required_fields' => array('lane', 'reason', 'action'),
        'production_telemetry' => false,
        'async_transport_lane' => 'native',
    ),
    'unified_routing' => array(
        'authority' => 'declarative-rule-table',
        'policy_builder' => 'ultracache_build_unified_js_execution_policy',
        'policy_evaluator' => 'ultracache_evaluate_unified_js_execution_policy',
        'registered_facts' => 'ultracache_build_registered_script_policy_facts',
        'dynamic_interpreter' => 'evaluateUnifiedDynamicPolicy',
        'separate_dynamic_precedence_tree' => false,
        'policy_payload_is_server_generated' => true,
        'environment_specific_facts_may_differ' => true,
        'production_telemetry' => false,
    ),
    'runtime_registry' => array(
        'entry_point' => 'ultracache_frontend_runtime_modules',
        'definitions' => 'ultracache_frontend_runtime_module_definitions',
        'fields' => array('handle', 'asset', 'enabled', 'lane', 'dependencies', 'reason'),
        'production_telemetry' => false,
        'activation_authority' => 'runtime_bundle_registry',
    ),
    'runtime_bundles' => array(
        'lanes' => array('native', 'defer', 'delay'),
        'max_normal_path_network_assets_per_lane' => 1,
        'inactive_module_source_loading' => false,
        'generated_asset_root' => 'uploads/ultracache/js-bundles',
        'content_addressed_variants' => true,
        'standalone_fallback_on_generation_failure' => true,
        'production_telemetry' => false,
    ),
    'consent_policy' => array(
        'hidden_control_plane_classifier' => false,
        'hidden_native_lifecycle_override' => false,
        'dynamic_tracker_gate' => false,
        'vendor_fingerprint_changes_lane' => false,
        'consent_assets_follow_normal_router_and_visible_policy' => true,
        'consent_original_wp_id_is_family_topology_provenance' => true,
        'cmp_owned_companion_prevents_independent_consumer_schedule' => true,
        'consent_family_handoff' => 'native-cmp-visible',
    ),
    'native_lane' => array(
        'audit_complete' => true,
        'normal_production_modules' => array(
            'dynamic-script-finder-bootstrap',
            'delayed-js-interaction-bootstrap',
            'lcp-request-credentials-bootstrap',
        ),
        'diagnostic_only_modules' => array(
            'runtime-js-scan-collector',
        ),
        'parser_early_requirement' => 'unrecoverable_pre_defer_information_or_explicit_diagnostic_capture',
        'optimization_opportunity_alone_is_not_enough' => true,
    ),
    'dynamic_script_finder' => array(
        'module' => 'dynamic-script-finder-bootstrap',
        'bootstrap_lane' => 'native',
        'bootstrap_policy' => 'visible_native_and_author_optout_else_capture_inert',
        'classifier_owner' => 'unified-policy-table-via-delayed-js-loader',
        'classifier_lane' => 'defer',
        'network_assets_added' => 0,
        'production_telemetry' => false,
        'vendor_identity_policy' => false,
        'visible_policy_precedence' => array('native_list', 'defer_list', 'default_lane'),
        'delay_executor' => 'delayed-js-loader',
        'covered_paths' => array('direct_appendChild', 'direct_insertBefore', 'direct_replaceChild', 'connected_src_assignment', 'complete_document_write'),
        'generic_subtree_recursive_scan' => false,
        'detached_script_dispatch' => 'bounded_pending_connected_list',
    ),
    'allowed_hidden_exception_categories' => array(
        'html_js_semantics',
        'explicit_author_opt_out',
        'explicit_integration_switch',
    ),
    'explicit_integrations' => array(
        'elementor' => 'protectElementorCompatibilityEnabled',
        'wpbakery' => 'protectWpBakeryAnimationsEnabled',
        'woocommerce_variable_products' => 'woocommerceVariableProductCompatibilityEnabled',
        'real_cookie_banner' => 'realCookieBannerCompatibilityEnabled',
        'complianz' => 'complianzCompatibilityEnabled',
    ),
    'forbidden_generic_policy_bases' => array(
        'vendor_identity',
        'plugin_path_identity',
        'hardcoded_vendor_handle',
        'consent_or_cmp_fingerprint',
        'ultracache_ownership_alone',
    ),
    'visible_policy' => array(
        'precedence' => array('native_list', 'defer_list', 'default_lane'),
        'native_wins_on_overlap' => true,
        'post_list_hidden_lane_override' => false,
        'defaults_are_user_editable' => true,
        'delay' => array(
            'default_lane' => 'delay',
            'defer_list' => 'Defer Instead of Delay',
            'native_list' => 'Do Not Defer or Delay',
        ),
        'defer' => array(
            'default_lane' => 'defer',
            'native_list' => 'Do Not Defer or Delay',
        ),
    ),
    'dependency_semantics' => array(
        'model' => 'lane-coherent-graph',
        'inline_companion_forces_native' => false,
        'has_dependent_forbids_delay' => false,
        'dependency_never_executes_later_than_dependent' => true,
        'inline_companions_follow_external_lane' => true,
        'dependency_connected_defer_transport' => 'ordered',
        'dependency_connected_delay_transport' => 'ordered',
        'parallel_execution_independent_scripts_only' => true,
        'promotion_direction' => 'earlier-only',
        'vendor_identity_policy' => false,
    ),
    'final_vendor_policy_audit' => array(
        'complete' => true,
        'hidden_vendor_scheduling_debt' => 0,
        'non_critical_classifier' => 'generic-semantic-only',
        'async_external_pattern_authority' => 'Delay third-party JS Patterns',
        'generic_exclusion_vendor_special_cases' => false,
        'generic_delay_loader_vendor_runtime' => false,
        'elementor_lazy_background_runtime' => array(
            'module' => 'elementor-compatibility-runtime',
            'lane' => 'defer',
            'activation' => 'explicit-elementor-compatibility-switch-and-active-delay-runtime',
        ),
    ),
    'scanner_policy' => array(
        'role' => 'teacher',
        'diagnostic_queue_is_policy_authority' => false,
        'stored_findings_affect_runtime' => false,
        'automatic_write_mode' => 'visible-setting-only',
        'automatic_apply_requires_policy_descriptor' => true,
        'hidden_override_storage' => false,
        'allowed_targets' => array(
            'delay' => array('lane' => 'delay', 'setting' => 'delaySafeThirdPartyJsPatterns', 'label' => 'Delay third-party JS Patterns'),
            'force' => array('lane' => 'defer', 'setting' => 'deferJsForceList', 'label' => 'Defer Instead of Delay'),
            'exclusion' => array('lane' => 'native', 'setting' => 'deferJsExcludeList', 'label' => 'Do Not Defer or Delay'),
        ),
        'manual_actions_write_drafts_only' => true,
        'production_telemetry' => false,
    ),
    'classification_audit_mode' => array(
        'verified_runtime_scan_only' => true,
        'production_telemetry' => false,
        'frontend_requests_added' => 0,
        'transport' => 'existing-runtime-scan-report',
        'record_fields' => array('url', 'handle', 'lane', 'reason', 'decisionSource', 'caughtBy', 'ruleId', 'matchedPattern', 'initiator'),
        'resource_request_source' => 'performance-resource-timing-script-entries',
        'unclassified_script_request_is_engine_bug' => true,
        'normal_production_dom_metadata' => false,
        'persistent_policy_storage' => false,
    ),
    'minimum_delay_release' => array(
        'setting' => 'delayedJsMinimumReleaseSeconds',
        'runtime_setting' => 'delayed_js_minimum_release_seconds',
        'default_seconds' => 0,
        'allowed_seconds' => array(0, 1, 2, 3, 4),
        'is_gate_not_trigger' => true,
        'clock_origin' => 'page_navigation_start',
        'interaction_request_is_retained' => true,
        'full_request_is_retained' => true,
        'interaction_precedes_pending_full_request' => true,
        'adds_frontend_request' => false,
    ),
    'frozen_existing_behavior' => array(
        // The existing Auto Release setting/timer is already correct. Minimum
        // Delay Release gates a requested release, but must not alter Auto
        // Release UI, defaults, migration, timer, trigger semantics, or
        // existing request generation.
        'auto_release' => 'unchanged',
    ),
);
